name: colonizethis_ai
description: AI behavior, planning, personalities for Colonize This.
version: 0.0.1
publish_to: none
repository: https://github.com/colonizethisv3/colonizethisv3
resolution: workspace

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  logger: ^2.0.2
  colonizethis_data:
  colonizethis_logic:
  colonizethis_models:

dev_dependencies:
  colonizethis_test:
  test: ^1.24.0
