name: ctdev
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0
resolution: workspace

environment:
  sdk: '>=3.11.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  basic_logger: ^0.2.3
  colonizethis_logger: any
  logger: ^2.0.2
  path: ^1.9.0
  path_provider: ^2.1.0
  hive: ^2.2.3
  colonizethis_ai: any
  colonizethis_logic: any
  colonizethis_models: any
  colonizethis_data: any
  colonizethis_map: any
  colonizethis_save: any

dev_dependencies:
  colonizethis_exception_lint:
    path: ../packages/colonizethis_exception_lint
  colonizethis_test:
  custom_lint: 0.8.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
