name: show_tech
description: "CLI tool to visualize the ColonizeThis tech tree."
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  colonizethis_data:

dev_dependencies:
  colonizethis_test:
  test: ^1.24.0
