// GENERATED FILE — do not edit by hand.
// Run: dart tool/generate_tech_effect_l10n.dart
// Then: cd app && flutter gen-l10n

import 'package:colonizethis_app_l10n/l10n/l10n.dart';
part of 'tech_effect_summary_lookup.dart';

Map<String, String Function(AppLocalizations)> _techEffectSummaryL10nChunk0() => {
  'techEffectSummary_advanced_hull_design_0': (l10n) => l10n.techEffectSummary_advanced_hull_design_0,
  'techEffectSummary_advanced_hull_design_1': (l10n) => l10n.techEffectSummary_advanced_hull_design_1,
  'techEffectSummary_advanced_iron_working_0': (l10n) => l10n.techEffectSummary_advanced_iron_working_0,
  'techEffectSummary_amalgamation_process_0': (l10n) => l10n.techEffectSummary_amalgamation_process_0,
  'techEffectSummary_amalgamation_process_1': (l10n) => l10n.techEffectSummary_amalgamation_process_1,
  'techEffectSummary_animal_husbandry_0': (l10n) => l10n.techEffectSummary_animal_husbandry_0,
  'techEffectSummary_animal_husbandry_1': (l10n) => l10n.techEffectSummary_animal_husbandry_1,
  'techEffectSummary_animal_husbandry_2': (l10n) => l10n.techEffectSummary_animal_husbandry_2,
  'techEffectSummary_apprentice_workers_0': (l10n) => l10n.techEffectSummary_apprentice_workers_0,
  'techEffectSummary_apprentice_workers_1': (l10n) => l10n.techEffectSummary_apprentice_workers_1,
  'techEffectSummary_banking_0': (l10n) => l10n.techEffectSummary_banking_0,
  'techEffectSummary_banking_1': (l10n) => l10n.techEffectSummary_banking_1,
  'techEffectSummary_bayonet_0': (l10n) => l10n.techEffectSummary_bayonet_0,
  'techEffectSummary_cigar_production_0': (l10n) => l10n.techEffectSummary_cigar_production_0,
  'techEffectSummary_cigar_production_1': (l10n) => l10n.techEffectSummary_cigar_production_1,
  'techEffectSummary_circular_saw_0': (l10n) => l10n.techEffectSummary_circular_saw_0,
  'techEffectSummary_circular_saw_1': (l10n) => l10n.techEffectSummary_circular_saw_1,
  'techEffectSummary_clipper_ships_0': (l10n) => l10n.techEffectSummary_clipper_ships_0,
  'techEffectSummary_coal_mining_0': (l10n) => l10n.techEffectSummary_coal_mining_0,
  'techEffectSummary_coal_mining_1': (l10n) => l10n.techEffectSummary_coal_mining_1,
  'techEffectSummary_convoying_0': (l10n) => l10n.techEffectSummary_convoying_0,
  'techEffectSummary_copper_and_tin_mining_0': (l10n) => l10n.techEffectSummary_copper_and_tin_mining_0,
  'techEffectSummary_copper_and_tin_mining_1': (l10n) => l10n.techEffectSummary_copper_and_tin_mining_1,
  'techEffectSummary_copper_and_tin_mining_2': (l10n) => l10n.techEffectSummary_copper_and_tin_mining_2,
  'techEffectSummary_cotton_gin_0': (l10n) => l10n.techEffectSummary_cotton_gin_0,
  'techEffectSummary_cotton_gin_1': (l10n) => l10n.techEffectSummary_cotton_gin_1,
  'techEffectSummary_cotton_planting_0': (l10n) => l10n.techEffectSummary_cotton_planting_0,
  'techEffectSummary_cotton_planting_1': (l10n) => l10n.techEffectSummary_cotton_planting_1,
  'techEffectSummary_cotton_weaving_0': (l10n) => l10n.techEffectSummary_cotton_weaving_0,
  'techEffectSummary_cotton_weaving_1': (l10n) => l10n.techEffectSummary_cotton_weaving_1,
  'techEffectSummary_crop_rotation_0': (l10n) => l10n.techEffectSummary_crop_rotation_0,
  'techEffectSummary_crucible_process_0': (l10n) => l10n.techEffectSummary_crucible_process_0,
  'techEffectSummary_crucible_process_1': (l10n) => l10n.techEffectSummary_crucible_process_1,
  'techEffectSummary_diplomatic_expertise_0': (l10n) => l10n.techEffectSummary_diplomatic_expertise_0,
  'techEffectSummary_diplomatic_expertise_1': (l10n) => l10n.techEffectSummary_diplomatic_expertise_1,
  'techEffectSummary_diplomatic_expertise_2': (l10n) => l10n.techEffectSummary_diplomatic_expertise_2,
  'techEffectSummary_discovery_of_cotton_0': (l10n) => l10n.techEffectSummary_discovery_of_cotton_0,
  'techEffectSummary_discovery_of_cotton_1': (l10n) => l10n.techEffectSummary_discovery_of_cotton_1,
  'techEffectSummary_discovery_of_furs_0': (l10n) => l10n.techEffectSummary_discovery_of_furs_0,
  'techEffectSummary_discovery_of_furs_1': (l10n) => l10n.techEffectSummary_discovery_of_furs_1,
  'techEffectSummary_discovery_of_gems_or_diamonds_0': (l10n) => l10n.techEffectSummary_discovery_of_gems_or_diamonds_0,
  'techEffectSummary_discovery_of_gems_or_diamonds_1': (l10n) => l10n.techEffectSummary_discovery_of_gems_or_diamonds_1,
  'techEffectSummary_discovery_of_gold_or_silver_0': (l10n) => l10n.techEffectSummary_discovery_of_gold_or_silver_0,
  'techEffectSummary_discovery_of_gold_or_silver_1': (l10n) => l10n.techEffectSummary_discovery_of_gold_or_silver_1,
  'techEffectSummary_discovery_of_spices_0': (l10n) => l10n.techEffectSummary_discovery_of_spices_0,
  'techEffectSummary_discovery_of_spices_1': (l10n) => l10n.techEffectSummary_discovery_of_spices_1,
  'techEffectSummary_discovery_of_sugar_0': (l10n) => l10n.techEffectSummary_discovery_of_sugar_0,
  'techEffectSummary_discovery_of_sugar_1': (l10n) => l10n.techEffectSummary_discovery_of_sugar_1,
  'techEffectSummary_discovery_of_tobacco_0': (l10n) => l10n.techEffectSummary_discovery_of_tobacco_0,
  'techEffectSummary_discovery_of_tobacco_1': (l10n) => l10n.techEffectSummary_discovery_of_tobacco_1,
  'techEffectSummary_dynamite_0': (l10n) => l10n.techEffectSummary_dynamite_0,
  'techEffectSummary_dynamite_1': (l10n) => l10n.techEffectSummary_dynamite_1,
  'techEffectSummary_early_rifles_0': (l10n) => l10n.techEffectSummary_early_rifles_0,
  'techEffectSummary_early_rifles_1': (l10n) => l10n.techEffectSummary_early_rifles_1,
};

