// GENERATED FILE — do not edit by hand.
// Run: dart tool/generate_tech_effect_l10n.dart
// Then: cd app && flutter gen-l10n

import 'package:colonizethis_app_l10n/l10n/l10n.dart';
part of 'tech_effect_summary_lookup.dart';

Map<String, String Function(AppLocalizations)> _techEffectSummaryL10nChunk2() => {
  'techEffectSummary_large_copper_and_tin_mines_1': (l10n) => l10n.techEffectSummary_large_copper_and_tin_mines_1,
  'techEffectSummary_large_copper_and_tin_mines_2': (l10n) => l10n.techEffectSummary_large_copper_and_tin_mines_2,
  'techEffectSummary_large_cotton_plantations_0': (l10n) => l10n.techEffectSummary_large_cotton_plantations_0,
  'techEffectSummary_large_cotton_plantations_1': (l10n) => l10n.techEffectSummary_large_cotton_plantations_1,
  'techEffectSummary_large_hulls_0': (l10n) => l10n.techEffectSummary_large_hulls_0,
  'techEffectSummary_large_precious_stone_mines_0': (l10n) => l10n.techEffectSummary_large_precious_stone_mines_0,
  'techEffectSummary_large_precious_stone_mines_1': (l10n) => l10n.techEffectSummary_large_precious_stone_mines_1,
  'techEffectSummary_large_spice_plantations_0': (l10n) => l10n.techEffectSummary_large_spice_plantations_0,
  'techEffectSummary_large_spice_plantations_1': (l10n) => l10n.techEffectSummary_large_spice_plantations_1,
  'techEffectSummary_large_sugar_plantations_0': (l10n) => l10n.techEffectSummary_large_sugar_plantations_0,
  'techEffectSummary_large_sugar_plantations_1': (l10n) => l10n.techEffectSummary_large_sugar_plantations_1,
  'techEffectSummary_large_tobacco_plantations_0': (l10n) => l10n.techEffectSummary_large_tobacco_plantations_0,
  'techEffectSummary_large_tobacco_plantations_1': (l10n) => l10n.techEffectSummary_large_tobacco_plantations_1,
  'techEffectSummary_later_steam_engine_0': (l10n) => l10n.techEffectSummary_later_steam_engine_0,
  'techEffectSummary_later_steam_engine_1': (l10n) => l10n.techEffectSummary_later_steam_engine_1,
  'techEffectSummary_light_artillery_tactics_0': (l10n) => l10n.techEffectSummary_light_artillery_tactics_0,
  'techEffectSummary_light_artillery_tactics_1': (l10n) => l10n.techEffectSummary_light_artillery_tactics_1,
  'techEffectSummary_long_range_rifles_0': (l10n) => l10n.techEffectSummary_long_range_rifles_0,
  'techEffectSummary_master_artisans_0': (l10n) => l10n.techEffectSummary_master_artisans_0,
  'techEffectSummary_master_artisans_1': (l10n) => l10n.techEffectSummary_master_artisans_1,
  'techEffectSummary_merchant_companies_0': (l10n) => l10n.techEffectSummary_merchant_companies_0,
  'techEffectSummary_merchant_companies_1': (l10n) => l10n.techEffectSummary_merchant_companies_1,
  'techEffectSummary_merchant_companies_2': (l10n) => l10n.techEffectSummary_merchant_companies_2,
  'techEffectSummary_merchant_steamships_0': (l10n) => l10n.techEffectSummary_merchant_steamships_0,
  'techEffectSummary_mine_engineering_0': (l10n) => l10n.techEffectSummary_mine_engineering_0,
  'techEffectSummary_mine_engineering_1': (l10n) => l10n.techEffectSummary_mine_engineering_1,
  'techEffectSummary_modern_forts_0': (l10n) => l10n.techEffectSummary_modern_forts_0,
  'techEffectSummary_modern_forts_1': (l10n) => l10n.techEffectSummary_modern_forts_1,
  'techEffectSummary_modern_military_funding_0': (l10n) => l10n.techEffectSummary_modern_military_funding_0,
  'techEffectSummary_modern_military_funding_1': (l10n) => l10n.techEffectSummary_modern_military_funding_1,
  'techEffectSummary_moldboard_plow_0': (l10n) => l10n.techEffectSummary_moldboard_plow_0,
  'techEffectSummary_moldboard_plow_1': (l10n) => l10n.techEffectSummary_moldboard_plow_1,
  'techEffectSummary_money_lending_0': (l10n) => l10n.techEffectSummary_money_lending_0,
  'techEffectSummary_money_lending_1': (l10n) => l10n.techEffectSummary_money_lending_1,
  'techEffectSummary_money_lending_2': (l10n) => l10n.techEffectSummary_money_lending_2,
  'techEffectSummary_national_bureaucracy_0': (l10n) => l10n.techEffectSummary_national_bureaucracy_0,
  'techEffectSummary_national_bureaucracy_1': (l10n) => l10n.techEffectSummary_national_bureaucracy_1,
  'techEffectSummary_national_bureaucracy_2': (l10n) => l10n.techEffectSummary_national_bureaucracy_2,
  'techEffectSummary_nationalism_0': (l10n) => l10n.techEffectSummary_nationalism_0,
  'techEffectSummary_nationalism_1': (l10n) => l10n.techEffectSummary_nationalism_1,
  'techEffectSummary_nationalism_2': (l10n) => l10n.techEffectSummary_nationalism_2,
  'techEffectSummary_navigation_0': (l10n) => l10n.techEffectSummary_navigation_0,
  'techEffectSummary_needle_guns_0': (l10n) => l10n.techEffectSummary_needle_guns_0,
  'techEffectSummary_needle_guns_1': (l10n) => l10n.techEffectSummary_needle_guns_1,
  'techEffectSummary_organised_regiments_0': (l10n) => l10n.techEffectSummary_organised_regiments_0,
  'techEffectSummary_organised_regiments_1': (l10n) => l10n.techEffectSummary_organised_regiments_1,
  'techEffectSummary_paddlewheels_0': (l10n) => l10n.techEffectSummary_paddlewheels_0,
  'techEffectSummary_precious_metals_mining_0': (l10n) => l10n.techEffectSummary_precious_metals_mining_0,
  'techEffectSummary_precious_metals_mining_1': (l10n) => l10n.techEffectSummary_precious_metals_mining_1,
  'techEffectSummary_precious_stone_mining_0': (l10n) => l10n.techEffectSummary_precious_stone_mining_0,
  'techEffectSummary_precious_stone_mining_1': (l10n) => l10n.techEffectSummary_precious_stone_mining_1,
  'techEffectSummary_printing_press_0': (l10n) => l10n.techEffectSummary_printing_press_0,
  'techEffectSummary_printing_press_1': (l10n) => l10n.techEffectSummary_printing_press_1,
  'techEffectSummary_privateering_companies_0': (l10n) => l10n.techEffectSummary_privateering_companies_0,
};

