import 'package:colonizethis_test/test.dart';

import 'package:ga_runner/ga_runner.dart';

/// Sentinel distinguishing an omitted `seed` key from an explicit `null`.
const Object _absent = Object();

void main() {
  group('GaConfig.fromJson', () {
    test('parses valid 2-player config', () {
      final config = GaConfig.fromJson(<String, dynamic>{
        'seed_profiles_dir': 'seeds/',
        'seed': 7,
        'game_player_count': 2,
        'game_setup_config': <String, dynamic>{
          'selectedGreatPowerIds': <String>['england', 'france'],
          'minorNationCount': 3,
          'tribeCount': 3,
          'numProvincesOldWorld': 23,
          'numProvincesNewWorld': 12,
        },
      });
      expect(config.gamePlayerCount, 2);
      expect(config.populationSize, 20);
      expect(config.gameSetupConfig.selectedGreatPowerIds.length, 2);
      expect(config.gameSetupConfig.numProvincesOldWorld, 23);
      expect(config.gameSetupConfig.minorNationCount, 3);
      expect(config.gameSetupConfig.tribeCount, 3);
    });

    test('derives numProvincesOldWorld from profile builder (ignores stale JSON)', () {
      final config = GaConfig.fromJson(<String, dynamic>{
        'seed_profiles_dir': 'seeds/',
        'seed': 7,
        'game_player_count': 2,
        'game_setup_config': <String, dynamic>{
          'selectedGreatPowerIds': <String>['england', 'france'],
          'minorNationCount': 3,
          'tribeCount': 3,
          'numProvincesOldWorld': 20,
          'numProvincesNewWorld': 12,
        },
      });
      expect(config.gameSetupConfig.numProvincesOldWorld, 23);
    });

    test('rejects orphan continents via profile builder', () {
      expect(
        () => GaConfig.fromJson(<String, dynamic>{
          'seed_profiles_dir': 'seeds/',
          'seed': 7,
          'game_player_count': 2,
          'game_setup_config': <String, dynamic>{
            'selectedGreatPowerIds': <String>['england', 'france'],
            'minorNationCount': 3,
            'tribeCount': 3,
            'continentCount': 6,
            'numProvincesNewWorld': 12,
          },
        }),
        throwsA(
          isA<FormatException>().having(
            (e) => e.message,
            'message',
            contains('orphan continents'),
          ),
        ),
      );
    });

    Map<String, dynamic> configWith({
      required int minorNationCount,
      required int tribeCount,
    }) => <String, dynamic>{
      'seed_profiles_dir': 'seeds/',
      'seed': 7,
      'game_player_count': 2,
      'game_setup_config': <String, dynamic>{
        'selectedGreatPowerIds': <String>['england', 'france'],
        'minorNationCount': minorNationCount,
        'tribeCount': tribeCount,
        'numProvincesOldWorld': 23,
        'numProvincesNewWorld': 12,
      },
    };

    for (final minors in <int>[0, 1, 2]) {
      test('rejects minorNationCount $minors (below minimum 3)', () {
        expect(
          () => GaConfig.fromJson(
            configWith(minorNationCount: minors, tribeCount: 3),
          ),
          throwsA(
            isA<FormatException>().having(
              (e) => e.message,
              'message',
              contains('minorNationCount'),
            ),
          ),
        );
      });
    }

    for (final tribes in <int>[0, 1, 2]) {
      test('rejects tribeCount $tribes (below minimum 3)', () {
        expect(
          () => GaConfig.fromJson(
            configWith(minorNationCount: 3, tribeCount: tribes),
          ),
          throwsA(
            isA<FormatException>().having(
              (e) => e.message,
              'message',
              contains('tribeCount'),
            ),
          ),
        );
      });
    }

    Map<String, dynamic> validConfig({Object? seed = 7}) => <String, dynamic>{
      'seed_profiles_dir': 'seeds/',
      if (seed != _absent) 'seed': seed,
      'game_player_count': 2,
      'game_setup_config': <String, dynamic>{
        'selectedGreatPowerIds': <String>['england', 'france'],
        'minorNationCount': 3,
        'tribeCount': 3,
        'numProvincesOldWorld': 23,
        'numProvincesNewWorld': 12,
      },
    };

    test('generates an entropy master seed when seed key is omitted (#3486)', () {
      final config = GaConfig.fromJson(validConfig(seed: _absent));
      expect(config.seedAutoGenerated, isTrue);
      expect(config.seed, inInclusiveRange(0, 0xFFFFFFFF));
    });

    test('generates an entropy master seed when seed is null (#3486)', () {
      final config = GaConfig.fromJson(validConfig(seed: null));
      expect(config.seedAutoGenerated, isTrue);
      expect(config.seed, inInclusiveRange(0, 0xFFFFFFFF));
    });

    test('resolved entropy seed is serialized as an integer in toJson (#3486)', () {
      final config = GaConfig.fromJson(validConfig(seed: _absent));
      expect(config.toJson()['seed'], isA<int>());
      expect(config.toJson()['seed'], config.seed);
    });

    test('preserves an explicit integer seed and marks it provided (#3486)', () {
      final config = GaConfig.fromJson(validConfig(seed: 7));
      expect(config.seed, 7);
      expect(config.seedAutoGenerated, isFalse);
      expect(config.toJson()['seed'], 7);
    });

    test('re-parsing toJson preserves an entropy seed as provided (resume, #3486)', () {
      final resolved = GaConfig.fromJson(validConfig(seed: _absent));
      final resumed = GaConfig.fromJson(resolved.toJson());
      expect(resumed.seed, resolved.seed);
      expect(resumed.seedAutoGenerated, isFalse);
    });

    for (final badSeed in <Object>['abc', 1.5, true]) {
      test('rejects non-integer seed ${badSeed.runtimeType} (#3486)', () {
        expect(
          () => GaConfig.fromJson(validConfig(seed: badSeed)),
          throwsA(
            isA<FormatException>().having(
              (e) => e.message,
              'message',
              contains('seed must be an integer'),
            ),
          ),
        );
      });
    }

    test('rejects non-2-player game_player_count in v1', () {
      expect(
        () => GaConfig.fromJson(<String, dynamic>{
          'seed_profiles_dir': 'seeds/',
          'seed': 1,
          'game_player_count': 6,
          'game_setup_config': <String, dynamic>{
            'selectedGreatPowerIds': <String>[
              'england',
              'france',
              'spain',
              'portugal',
              'netherlands',
              'prussia',
            ],
          },
        }),
        throwsA(isA<FormatException>()),
      );
    });

    test('parses seven_gp defaults and derives 7-GP setup', () {
      final config = GaConfig.fromJson(<String, dynamic>{
        'seed_profiles_dir': 'seeds/',
        'seed': 7,
        'game_player_count': 2,
        'game_setup_config': <String, dynamic>{
          'selectedGreatPowerIds': <String>['england', 'france'],
          'minorNationCount': 3,
          'tribeCount': 3,
        },
      });
      expect(config.sevenGpGamesPerProfile, 1);
      expect(config.stageFitnessWeights.twoPlayer, 0.5);
      expect(config.sevenGpGameSetupConfig.greatPowerCount, 7);
      expect(config.sevenGpFallbackDefaultAiSeats, 3);
    });

    test('rejects invalid stage fitness weights', () {
      expect(
        () => GaConfig.fromJson(<String, dynamic>{
          'seed_profiles_dir': 'seeds/',
          'seed': 7,
          'game_player_count': 2,
          'stage_fitness_weights': <String, dynamic>{'two_player': 0},
          'game_setup_config': <String, dynamic>{
            'selectedGreatPowerIds': <String>['england', 'france'],
            'minorNationCount': 3,
            'tribeCount': 3,
          },
        }),
        throwsA(isA<FormatException>()),
      );
    });

    test('rejects fallback seat counts that do not sum to 6', () {
      expect(
        () => GaConfig.fromJson(<String, dynamic>{
          'seed_profiles_dir': 'seeds/',
          'seed': 7,
          'game_player_count': 2,
          'seven_gp_fallback_default_ai_seats': 2,
          'seven_gp_fallback_randomized_ai_seats': 2,
          'game_setup_config': <String, dynamic>{
            'selectedGreatPowerIds': <String>['england', 'france'],
            'minorNationCount': 3,
            'tribeCount': 3,
          },
        }),
        throwsA(isA<FormatException>()),
      );
    });

    test('parses seven_gp_use_blessed_profiles (Refs #3488)', () {
      final enabled = GaConfig.fromJson(<String, dynamic>{
        'seed_profiles_dir': 'seeds/',
        'seed': 7,
        'game_player_count': 2,
        'seven_gp_use_blessed_profiles': true,
        'game_setup_config': <String, dynamic>{
          'selectedGreatPowerIds': <String>['england', 'france'],
          'minorNationCount': 3,
          'tribeCount': 3,
        },
      });
      expect(enabled.sevenGpUseBlessedProfiles, isTrue);

      final disabled = GaConfig.fromJson(<String, dynamic>{
        'seed_profiles_dir': 'seeds/',
        'seed': 7,
        'game_player_count': 2,
        'game_setup_config': <String, dynamic>{
          'selectedGreatPowerIds': <String>['england', 'france'],
          'minorNationCount': 3,
          'tribeCount': 3,
        },
      });
      expect(disabled.sevenGpUseBlessedProfiles, isFalse);
    });

    test('prune_observer_traces defaults to false and round-trips', () {
      final defaulted = GaConfig.fromJson(<String, dynamic>{
        'seed_profiles_dir': 'seeds/',
        'seed': 7,
        'game_player_count': 2,
        'game_setup_config': <String, dynamic>{
          'selectedGreatPowerIds': <String>['england', 'france'],
          'minorNationCount': 3,
          'tribeCount': 3,
        },
      });
      expect(defaulted.pruneObserverTraces, isFalse);
      expect(defaulted.toJson()['prune_observer_traces'], isFalse);

      final enabled = GaConfig.fromJson(<String, dynamic>{
        'seed_profiles_dir': 'seeds/',
        'seed': 7,
        'game_player_count': 2,
        'prune_observer_traces': true,
        'game_setup_config': <String, dynamic>{
          'selectedGreatPowerIds': <String>['england', 'france'],
          'minorNationCount': 3,
          'tribeCount': 3,
        },
      });
      expect(enabled.pruneObserverTraces, isTrue);
      expect(enabled.toJson()['prune_observer_traces'], isTrue);
      final roundTripped = GaConfig.fromJson(enabled.toJson());
      expect(roundTripped.pruneObserverTraces, isTrue);
    });

    test('accepts random seven_gp_opponent_selection (Refs #3488)', () {
      final config = GaConfig.fromJson(<String, dynamic>{
        'seed_profiles_dir': 'seeds/',
        'seed': 7,
        'game_player_count': 2,
        'seven_gp_opponent_selection': 'random',
        'game_setup_config': <String, dynamic>{
          'selectedGreatPowerIds': <String>['england', 'france'],
          'minorNationCount': 3,
          'tribeCount': 3,
        },
      });
      expect(config.sevenGpOpponentSelection, 'random');
    });

    test('rejects unknown seven_gp_opponent_selection (Refs #3488)', () {
      expect(
        () => GaConfig.fromJson(<String, dynamic>{
          'seed_profiles_dir': 'seeds/',
          'seed': 7,
          'game_player_count': 2,
          'seven_gp_opponent_selection': 'most_wins',
          'game_setup_config': <String, dynamic>{
            'selectedGreatPowerIds': <String>['england', 'france'],
            'minorNationCount': 3,
            'tribeCount': 3,
          },
        }),
        throwsA(
          isA<FormatException>().having(
            (e) => e.message,
            'message',
            allOf(contains('top_fitness'), contains('random')),
          ),
        ),
      );
    });
  });
}
