// Development panel assign + road-first (Refs #4175). Dense for repo.orders_test_support_loc.
// dart format off
import 'package:colonizethis_data/colonizethis_data.dart';
import 'package:colonizethis_logic/colonizethis_logic.dart';
import 'package:colonizethis_models/colonizethis_models.dart';
import 'package:colonizethis_orders/colonizethis_orders.dart';
import 'package:colonizethis_orders/src/orders/order_suggestion_context.dart';
import 'package:colonizethis_test/test.dart';
import 'support/scenario_runner.dart';
import 'support/suggestion/order_suggestion_core_fixtures.dart';

TileMapResult _row3() => TileMapResult(width: 3, height: 1, grid: const [['p1', 'p1', 'p1']], terrainGrid: const [[TerrainType.plains, TerrainType.plains, TerrainType.plains]]);
DevelopmentAssignRowState _assignState(OscDualBuilderGrainTiles s, {Game? game, Orders orders = const Orders(), Set<String>? connected, Set<String>? tiles}) => resolveDevelopmentAssignRowState(game: game ?? s.game(), playerId: OscIds.playerId, currentOrders: orders, topology: s.topology(), tileMapByRegion: const {}, commodityTileKeys: tiles ?? {s.tileA}, connectedTileKeys: connected ?? {s.tileA});

void main() {
  runLabeledScenarioGroup('developmentPanelDense', [
    rs('orderDevelopmentImproveTiles prefers connected then lower level without maps', () {const ts = TileMapState(improvementByTile: {'oldWorld|p1|0|0': 1, 'oldWorld|p1|1|0': 0, 'oldWorld|p1|2|0': 0}); const c = {'oldWorld|p1|0|0', 'oldWorld|p1|1|0'}; expect(orderDevelopmentImproveTiles(game: oscGame(worldState: oscWorld(tileState: ts)), playerId: OscIds.playerId, tileKeys: const {'oldWorld|p1|2|0', 'oldWorld|p1|0|0', 'oldWorld|p1|1|0'}, connectedTileKeys: c, tileState: ts), ['oldWorld|p1|1|0', 'oldWorld|p1|0|0', 'oldWorld|p1|2|0']);}),
    rs('idleBuildersForDevelopmentAssign uses stable unit id order', () {final s = OscDualBuilderGrainTiles(); expect(idleBuildersForDevelopmentAssign(game: s.game(), playerId: OscIds.playerId, currentOrders: const Orders()).map((u) => u.id).toList(), ['b1', 'b2']);}),
    rs('idleBuildersForDevelopmentAssign excludes pending work units', () {final s = OscDualBuilderGrainTiles(); expect(idleBuildersForDevelopmentAssign(game: s.game(), playerId: OscIds.playerId, currentOrders: s.ordersReservingTileA()).map((u) => u.id).toList(), ['b2']);}),
    rs('selectDevelopmentImproveAssignCandidate picks first builder and reserved tile', () {final s = OscDualBuilderGrainTiles(); final c = selectDevelopmentImproveAssignCandidate(game: s.game(), playerId: OscIds.playerId, currentOrders: s.ordersReservingTileA(), topology: s.topology(), tileMapByRegion: const {}, commodityTileKeys: {s.tileA, s.tileB}, connectedTileKeys: {s.tileA, s.tileB}); expect(c, isNotNull); expect(c!.builderUnitId, 'b2'); expect(c.targetTileKey, s.tileB);}),
    rs('selectDevelopmentImproveAssignCandidate builds one validator per call', () {final s = OscDualBuilderGrainTiles(); resetIncrementalCandidateValidatorBuildCountForTests(); selectDevelopmentImproveAssignCandidate(game: s.game(), playerId: OscIds.playerId, currentOrders: s.ordersReservingTileA(), topology: s.topology(), tileMapByRegion: const {}, commodityTileKeys: {s.tileA, s.tileB}, connectedTileKeys: {s.tileA, s.tileB}); expect(incrementalCandidateValidatorBuildCountForTests, 1, reason: 'one pass-level build across builder loop (Refs #4258)');}),
    rs('resolveDevelopmentAssignRowState disables when materials insufficient', () {final s = OscDualBuilderGrainTiles(); final st = _assignState(s, game: s.game().copyWith(players: [s.player.copyWith(stockpile: const Stockpile())])); expect(st.enabled, isFalse); expect(st.disabledReason, 'Insufficient materials');}),
    rs('resolveDevelopmentAssignRowState enables with materials and connectivity', () {final s = OscDualBuilderGrainTiles(); final st = _assignState(s); expect(st.enabled, isTrue); expect(st.candidate?.builderUnitId, 'b1'); expect(st.candidate?.targetTileKey, s.tileA);}),
    rs('resolveDevelopmentAssignRowState enables disconnected commodity when materials allow', () {final s = OscDualBuilderGrainTiles(); final st = _assignState(s, connected: const {}); expect(st.enabled, isTrue); expect(st.candidate?.targetTileKey, s.tileA); expect(st.candidate?.isCapitalConnected, isFalse);}),
    rs('developmentPanelMaterialShortageCommodityIds flags blocked rows', () {final s = OscDualBuilderGrainTiles(); final g = s.game().copyWith(players: [s.player.copyWith(stockpile: const Stockpile())]); expect(developmentPanelMaterialShortageCommodityIds(game: g, playerId: OscIds.playerId, currentOrders: const Orders(), topology: s.topology(), tileMapByRegion: const {}, improvableRows: [(commodityId: 'grain', tileKeys: {s.tileA})], connectedTileKeys: {s.tileA}), {'grain'});}),
    rs('shortestOwnedTilePathToConnectedNetwork finds path on owned tiles', () {final t0 = OscIds.tile('p1', 0, 0), t1 = OscIds.tile('p1', 1, 0), t2 = OscIds.tile('p1', 2, 0); final g = oscGame(worldState: oscWorld(oldWorld: RegionData(provinces: [oscProvince('p1', ownerId: OscIds.playerId)]), tileKeysByRegionAndProvince: oscTilesByProvince({'p1': [t0, t1, t2]}))); expect(shortestOwnedTilePathToConnectedNetwork(game: g, playerId: OscIds.playerId, startTileKey: t2, connectedTileKeys: {t0}, tileMapByRegion: {'oldWorld': _row3()}, topology: oscProvinceTopology(['p1'])), [t2, t1, t0]);}),
    rs('resolveDevelopmentRoadFirstState disables without idle Engineers', () {final t0 = OscIds.tile('p1', 0, 0), t2 = OscIds.tile('p1', 2, 0); final g = oscGame(worldState: oscWorld(oldWorld: RegionData(provinces: [oscProvince('p1', ownerId: OscIds.playerId)], units: [oscBuilder(id: 'b1', provinceLocal: 'p1', tileKey: t0)]), tileKeysByRegionAndProvince: oscTilesByProvince({'p1': [t0, OscIds.tile('p1', 1, 0), t2]}))); final st = resolveDevelopmentRoadFirstState(game: g, playerId: OscIds.playerId, currentOrders: const Orders(), topology: oscProvinceTopology(['p1']), tileMapByRegion: {'oldWorld': _row3()}, improveTargetTileKey: t2, connectedTileKeys: {t0}); expect(st.enabled, isFalse); expect(st.disabledReason, 'No idle Engineers');}),
    rs('resolveDevelopmentRoadFirstState enables with engineer and materials', () {final t0 = OscIds.tile('p1', 0, 0), t1 = OscIds.tile('p1', 1, 0), t2 = OscIds.tile('p1', 2, 0); final g = oscGame(worldState: oscWorld(oldWorld: RegionData(provinces: [oscProvince('p1', ownerId: OscIds.playerId)], units: [Unit(id: 'e1', type: kUnitTypeEngineer, ownerId: OscIds.playerId, locationProvinceId: OscIds.prov('p1'), tileKey: t0)]), tileKeysByRegionAndProvince: oscTilesByProvince({'p1': [t0, t1, t2]}), playerVisibilityByTile: oscVisibility({t0: 'fullyVisible', t1: 'fullyVisible', t2: 'fullyVisible'})), players: [oscBuilderPlayer(lumberCastIron: 20)]); final st = resolveDevelopmentRoadFirstState(game: g, playerId: OscIds.playerId, currentOrders: const Orders(), topology: oscProvinceTopology(['p1']), tileMapByRegion: {'oldWorld': _row3()}, improveTargetTileKey: t2, connectedTileKeys: {t0}); expect(st.enabled, isTrue); expect(st.candidate?.engineerUnitId, 'e1'); expect(st.candidate?.targetTileKey, t1);}),
    rs('selectDevelopmentRoadFirstCandidate builds one validator per call', () {final t0 = OscIds.tile('p1', 0, 0), t1 = OscIds.tile('p1', 1, 0), t2 = OscIds.tile('p1', 2, 0); final g = oscGame(worldState: oscWorld(oldWorld: RegionData(provinces: [oscProvince('p1', ownerId: OscIds.playerId)], units: [Unit(id: 'e1', type: kUnitTypeEngineer, ownerId: OscIds.playerId, locationProvinceId: OscIds.prov('p1'), tileKey: t0)]), tileKeysByRegionAndProvince: oscTilesByProvince({'p1': [t0, t1, t2]}), playerVisibilityByTile: oscVisibility({t0: 'fullyVisible', t1: 'fullyVisible', t2: 'fullyVisible'})), players: [oscBuilderPlayer(lumberCastIron: 20)]); resetIncrementalCandidateValidatorBuildCountForTests(); selectDevelopmentRoadFirstCandidate(game: g, playerId: OscIds.playerId, currentOrders: const Orders(), topology: oscProvinceTopology(['p1']), tileMapByRegion: {'oldWorld': _row3()}, improveTargetTileKey: t2, connectedTileKeys: {t0}); expect(incrementalCandidateValidatorBuildCountForTests, 1, reason: 'one pass-level build across engineer loop (Refs #4258)');}),
  ], runRunnableScenario);
}
