// Industry counsel ranking (Refs #4189/#4190). Dense for repo.orders_test_support_loc.
// dart format off
import 'package:colonizethis_data/colonizethis_data.dart';
import 'package:colonizethis_economy/colonizethis_economy.dart';
import 'package:colonizethis_models/colonizethis_models.dart';
import 'package:colonizethis_orders/src/orders/industry_counsel_ranking.dart';
import 'package:colonizethis_test/test.dart';
import 'package:colonizethis_world/colonizethis_world.dart';
import 'support/scenario_runner.dart';

Game _icrGame({Stockpile? stockpile, WorkerPool? workers}) => Game(id: 'g1', players: [Player(id: 'gp1', displayName: 'GP', isHuman: true, stockpile: stockpile ?? const Stockpile(), workerPool: workers ?? const WorkerPool())], worldState: WorldState(turnState: const TurnState(phase: TurnPhase.orders, turnNumber: 0), oldWorld: const RegionData(), newWorld: const RegionData()));
List<IndustryCounselRecommendation> _icrRank(Game game, {Map<String, TileMapResult> tileMapByRegion = const {}}) => rankIndustryCounselRecommendations(game: game, playerId: 'gp1', currentOrders: const Orders(), topology: const MapTopology(), tileMapByRegion: tileMapByRegion);
int _icrKindPrecedence(IndustryCounselRecommendationKind kind) => switch (kind) {IndustryCounselRecommendationKind.produceRecipe => 0, IndustryCounselRecommendationKind.trainWorker => 1, IndustryCounselRecommendationKind.unblockFeedstock => 2};
const _icrFeedstockTileKey = 'oldWorld|p1|0|0';
final _icrFeedstockTileMap = {'oldWorld': TileMapResult(width: 1, height: 1, grid: const [['p1']], resourceGrid: const [[Resource.timber]], terrainGrid: const [[TerrainType.hardwoodForest]])};
Game _icrFeedstockStarvedGame() => Game(id: 'g-feedstock', players: [Player(id: 'gp1', displayName: 'GP', isHuman: true, stockpile: Stockpile().applyDelta(CommodityCatalog.grain.id, 8).applyDelta(CommodityCatalog.fabric.id, 8).applyDelta(CommodityCatalog.castIron.id, 8).applyDelta(CommodityCatalog.refinedSugar.id, 8).applyDelta(CommodityCatalog.cigars.id, 8).applyDelta(CommodityCatalog.furHats.id, 8).applyDelta(CommodityCatalog.steel.id, 8).applyDelta(CommodityCatalog.paper.id, 8).applyDelta(CommodityCatalog.bronze.id, 8), workerPool: const WorkerPool(peasants: 4), techUnlocked: const {'lumber_from_timber': true})], worldState: WorldState(turnState: const TurnState(phase: TurnPhase.orders, turnNumber: 0), oldWorld: RegionData(provinces: [Province(id: 'oldWorld|p1', regionId: 'oldWorld', ownerId: 'gp1')]), newWorld: const RegionData(), tileKeysByRegionAndProvince: const {'oldWorld': {'p1': [_icrFeedstockTileKey]}}, resourceByTileKey: const {_icrFeedstockTileKey: 'timber'}, tileState: const TileMapState(improvementByTile: {_icrFeedstockTileKey: 0})));
Game _icrCrossKindGame() => Game(id: 'g-cross', players: [Player(id: 'gp1', displayName: 'GP', isHuman: true, stockpile: Stockpile().applyDelta(CommodityCatalog.grain.id, 10).applyDelta(CommodityCatalog.sugarCane.id, 40).applyDelta(CommodityCatalog.timber.id, 50).applyDelta(CommodityCatalog.cotton.id, 50).applyDelta(CommodityCatalog.fabric.id, 6).applyDelta(CommodityCatalog.paper.id, 10), workerPool: const WorkerPool(peasants: 8), treasury: 1000, techUnlocked: const {kTechIdCottonWeaving: true, kTechIdApprenticeWorkers: true, kTechIdSugarRefining: true})], worldState: WorldState(turnState: const TurnState(phase: TurnPhase.orders, turnNumber: 0), oldWorld: const RegionData(), newWorld: const RegionData()));

void main() {
  runLabeledScenarioGroup('rankIndustryCounselRecommendations', [
    rs('returns at most three stable recommendations', () {final g = _icrGame(stockpile: Stockpile().applyDelta(CommodityCatalog.timber.id, 20).applyDelta(CommodityCatalog.fabric.id, 10), workers: const WorkerPool(peasants: 4)); final first = _icrRank(g); expect(first.length, lessThanOrEqualTo(3)); expect(_icrRank(g), equals(first)); for (final r in first) {expect(r.recommendationId, isNotEmpty); expect(r.detailReasonKeys, isNotEmpty);}}),
    rs('stars only produce recipes in ranked produce slots', () {final produce = _icrRank(_icrGame(stockpile: Stockpile().applyDelta(CommodityCatalog.timber.id, 30).applyDelta(CommodityCatalog.iron.id, 30).applyDelta(CommodityCatalog.coal.id, 30), workers: const WorkerPool(peasants: 8))).where((r) => r.kind == IndustryCounselRecommendationKind.produceRecipe).toList(); expect(produce.length, lessThanOrEqualTo(3)); for (final r in produce) {expect(r.recipeId, isNotNull); expect(r.recommendationId, startsWith('produce:'));}}),
    rs('sorts merged candidates by descending rankScore', () {final ranked = _icrRank(_icrGame(stockpile: Stockpile().applyDelta(CommodityCatalog.timber.id, 20).applyDelta(CommodityCatalog.fabric.id, 10), workers: const WorkerPool(peasants: 4))); for (var i = 0; i < ranked.length - 1; i++) {expect(ranked[i].rankScore, greaterThanOrEqualTo(ranked[i + 1].rankScore)); if (ranked[i].rankScore == ranked[i + 1].rankScore) {expect(_icrKindPrecedence(ranked[i].kind), lessThanOrEqualTo(_icrKindPrecedence(ranked[i + 1].kind)));}}}),
    rs('merges produce and train with unified descending rankScore sort', () {final ranked = _icrRank(_icrCrossKindGame()); expect(ranked.length, 3); expect(ranked.where((r) => r.kind == IndustryCounselRecommendationKind.produceRecipe).length, 2); expect(ranked.singleWhere((r) => r.kind == IndustryCounselRecommendationKind.trainWorker).trainTier, WorkerTier.apprentice); expect(ranked.first.kind, IndustryCounselRecommendationKind.produceRecipe); expect(ranked.last.kind, IndustryCounselRecommendationKind.trainWorker); for (var i = 0; i < ranked.length - 1; i++) {expect(ranked[i].rankScore, greaterThanOrEqualTo(ranked[i + 1].rankScore)); if (ranked[i].rankScore == ranked[i + 1].rankScore) {expect(_icrKindPrecedence(ranked[i].kind), lessThanOrEqualTo(_icrKindPrecedence(ranked[i + 1].kind)));}}}),
    rs('emits one unblockFeedstock when produce is input-starved and improvable timber exists', () {final ranked = _icrRank(_icrFeedstockStarvedGame(), tileMapByRegion: _icrFeedstockTileMap); final feedstock = ranked.where((r) => r.kind == IndustryCounselRecommendationKind.unblockFeedstock).toList(); expect(feedstock, hasLength(1)); final rec = feedstock.single; expect(rec.recommendationId, 'feedstock:${CommodityCatalog.timber.id}'); expect(rec.briefReasonKey, IndustryCounselReasonKey.feedstockBlocked); expect(rec.detailReasonKeys, [IndustryCounselReasonKey.feedstockBlocked]); expect(rec.feedstockDeepLink?.commodityId, CommodityCatalog.timber.id); expect(rec.feedstockDeepLink?.highlightTileKey, _icrFeedstockTileKey); for (var i = 0; i < ranked.length - 1; i++) {expect(ranked[i].rankScore, greaterThanOrEqualTo(ranked[i + 1].rankScore)); if (ranked[i].rankScore == ranked[i + 1].rankScore) {expect(_icrKindPrecedence(ranked[i].kind), lessThanOrEqualTo(_icrKindPrecedence(ranked[i + 1].kind)));}}}),
  ], runRunnableScenario);
  runLabeledScenarioGroup('industryCounselScoreRecipe', [
    rs('neutral agenda yields zero agenda contribution', () {final recipe = ProductionRecipesCatalog.byId['lumber_from_timber']!; final neutral = industryCounselScoreRecipe(recipe: recipe, stockpile: const Stockpile(), workers: const WorkerPool(), agendaId: kIndustryCounselNeutralAgendaId); expect(industryCounselScoreRecipe(recipe: recipe, stockpile: const Stockpile(), workers: const WorkerPool(), agendaId: 'warmonger'), greaterThan(neutral));}),
  ], runRunnableScenario);
}
