name: colonizethis_models
description: Shared data models, schemas, serialization for Colonize This.
version: 0.0.1
publish_to: none
repository: https://github.com/colonizethisv3/colonizethisv3
resolution: workspace

environment:
  sdk: '>=3.11.5 <4.0.0'

dev_dependencies:
  colonizethis_data:
    path: ../colonizethis_data
  colonizethis_exception_lint:
    path: ../colonizethis_exception_lint
  colonizethis_test:
  coverage: ^1.15.0
  custom_lint: ^0.8.1
  test: ^1.24.0

dependencies:
  colonizethis_logger: any
