import 'colonial_phase_planner_acquisition_join_empire_branch_cases.dart';
import 'colonial_phase_planner_acquisition_join_empire_tail_cases.dart';

void registerColonialPhasePlannerAcquisitionJoinEmpireCases() {
  registerColonialPhasePlannerAcquisitionJoinEmpireCasesPartA();
  registerColonialPhasePlannerAcquisitionJoinEmpireCasesPartB();
}
