// Case-library barrel (Refs #4365 Slice B densify).

import 'economy_planner_regiment_build_input_production_feedstock_staging_part_a_cases.dart';
import 'economy_planner_regiment_build_input_production_feedstock_staging_part_b_cases.dart';

void registerEconomyPlannerRegimentBuildInputProductionFeedstockStagingCases() {
  registerEconomyPlannerRegimentBuildInputProductionFeedstockStagingCasesPartA();
  registerEconomyPlannerRegimentBuildInputProductionFeedstockStagingCasesPartB();
}
