// Case-library barrel (Refs #4602 Slice B).

import 'expand_phase_planner_survival_stubs_delegating_peace_guard_cases.dart';
import 'expand_phase_planner_survival_stubs_delegating_peace_delegation_match_cases.dart';
import 'expand_phase_planner_survival_stubs_delegating_peace_stalled_zero_stub_cases.dart';
import 'expand_phase_planner_survival_stubs_delegating_peace_mutual_stalemate_stub_cases.dart';

void registerExpandSurvivalStubsDelegatingPeaceCases() {
  registerExpandSurvivalStubsDelegatingPeaceGuardCases();
  registerExpandSurvivalStubsDelegatingPeaceDelegationMatchCases();
  registerExpandSurvivalStubsDelegatingPeaceStalledZeroStubCases();
  registerExpandSurvivalStubsDelegatingPeaceMutualStalemateStubCases();
}
