// Case-library barrel (Refs #4602 Slice B).

import 'expand_phase_planner_near_quota_peace_nearquotaholdpeacetargets_outer_guards_cases.dart';
import 'expand_phase_planner_near_quota_peace_nearquotaholdpeacetargets_sole_gp_arm_cases.dart';
import 'expand_phase_planner_near_quota_peace_nearquotaholdpeacetargets_multi_gp_arm_cases.dart';
import 'expand_phase_planner_near_quota_peace_nearquotaholdpeacetargets_determinism_de_cases.dart';

void registerExpandNearQuotaPeaceCases() {
  registerNearQuotaPeaceNearquotaholdpeacetargetsOuterGuardsCases();
  registerNearQuotaPeaceNearquotaholdpeacetargetsSoleGpArmCases();
  registerNearQuotaPeaceNearquotaholdpeacetargetsMultiGpArmCases();
  registerNearQuotaPeaceNearquotaholdpeacetargetsDeterminismDeCases();
}
