// Case-library barrel (Refs #4602 Slice B).

import 'expand_phase_planner_critical_weak_survival_peace_guard_cases.dart';
import 'expand_phase_planner_critical_weak_survival_peace_default_start_cases.dart';
import 'expand_phase_planner_critical_weak_survival_peace_below_quota_cases.dart';
import 'expand_phase_planner_critical_weak_survival_peace_fire_cases.dart';
import 'expand_phase_planner_critical_weak_survival_peace_delegation_cases.dart';
import 'expand_phase_planner_critical_weak_survival_peace_determinism_cases.dart';

void registerExpandPhasePlannerCriticalWeakSurvivalPeaceCases() {
  registerExpandPhasePlannerCriticalWeakSurvivalPeaceGuardCases();
  registerExpandPhasePlannerCriticalWeakSurvivalPeaceDefaultStartCases();
  registerExpandPhasePlannerCriticalWeakSurvivalPeaceBelowQuotaCases();
  registerExpandPhasePlannerCriticalWeakSurvivalPeaceFireCases();
  registerExpandPhasePlannerCriticalWeakSurvivalPeaceDelegationCases();
  registerExpandPhasePlannerCriticalWeakSurvivalPeaceDeterminismCases();
}
