// Case-library barrel (Refs #4602 Slice B).

import 'expand_phase_planner_critical_multi_front_peace_criticalmultifrontgppeacetargets_canonic_cases.dart';
import 'expand_phase_planner_critical_multi_front_peace_criticalmultifrontgppeacetargets_stub_de_cases.dart';
import 'expand_phase_planner_critical_multi_front_peace_criticalmultifrontgppeacetargets_determi_cases.dart';

void registerExpandPhasePlannerCriticalMultiFrontPeaceCases() {
  registerCriticalMultiFrontPeaceCriticalmultifrontgppeacetargetsCanonicCases();
  registerCriticalMultiFrontPeaceCriticalmultifrontgppeacetargetsStubDeCases();
  registerCriticalMultiFrontPeaceCriticalmultifrontgppeacetargetsDetermiCases();
}
