// Case-library barrel (Refs #4602 Slice B).

import 'expand_phase_planner_quota_met_peace_deciders_futile_quotametfutilebelowquotagppeacetargets_o_cases.dart';
import 'expand_phase_planner_quota_met_peace_deciders_futile_quotametfutilebelowquotagppeacetargets_p_cases.dart';
import 'expand_phase_planner_quota_met_peace_deciders_futile_quotametfutilebelowquotagppeacetargets_m_cases.dart';

void registerExpandPhasePlannerQuotaMetPeaceDecidersFutileCases() {
  registerQuotaMetPeaceDecidersFutileQuotametfutilebelowquotagppeacetargetsOCases();
  registerQuotaMetPeaceDecidersFutileQuotametfutilebelowquotagppeacetargetsPCases();
  registerQuotaMetPeaceDecidersFutileQuotametfutilebelowquotagppeacetargetsMCases();
}
