import 'expand_phase_planner_critical_ow_hold_and_stalled_lead_peace_part_a_cases.dart';
import 'expand_phase_planner_critical_ow_hold_and_stalled_lead_peace_part_b_cases.dart';

void registerExpandPhasePlannerCriticalOwHoldAndStalledLeadPeaceCases() {
  registerExpandPhasePlannerCriticalOwHoldAndStalledLeadPeaceCasesPartA();
  registerExpandPhasePlannerCriticalOwHoldAndStalledLeadPeaceCasesPartB();
}
