// Case-library barrel (Refs #4602 Slice B).

import 'expand_phase_planner_below_quota_multi_minor_distraction_fire_fire_cases.dart';
import 'expand_phase_planner_below_quota_multi_minor_distraction_fire_determinism_cases.dart';
import 'expand_phase_planner_below_quota_multi_minor_distraction_fire_delegation_cases.dart';

void registerExpandPhasePlannerBelowQuotaMultiMinorDistractionFireCases() {
  registerExpandPhasePlannerBelowQuotaMultiMinorDistractionFireFireCases();
  registerExpandPhasePlannerBelowQuotaMultiMinorDistractionFireDeterminismCases();
  registerExpandPhasePlannerBelowQuotaMultiMinorDistractionFireDelegationCases();
}
