// Case-library barrel (Refs #4602 Slice B).

import 'expand_phase_planner_sole_gp_peace_deciders_unwinnable_unwinnablesolegpfrontierpeacetarget_sole_cases.dart';
import 'expand_phase_planner_sole_gp_peace_deciders_unwinnable_unwinnablesolegpfrontierpeacetarget_quot_cases.dart';
import 'expand_phase_planner_sole_gp_peace_deciders_unwinnable_unwinnablesolegpfrontierpeacetarget_defi_cases.dart';

void registerExpandSoleGpPeaceDecidersUnwinnableCases() {
  registerSoleGpPeaceDecidersUnwinnableUnwinnablesolegpfrontierpeacetargetSoleCases();
  registerSoleGpPeaceDecidersUnwinnableUnwinnablesolegpfrontierpeacetargetQuotCases();
  registerSoleGpPeaceDecidersUnwinnableUnwinnablesolegpfrontierpeacetargetDefiCases();
}
