// Case bodies for resolvePhaseEconomyExpandBelowQuotaPeaceInsufficientRegimentsActive
// pins in `phase_planner_economy_filter_below_quota_peace_test.dart`.

import 'phase_planner_economy_filter_below_quota_peace_insufficient_regiments_parity_cases.dart';
import 'phase_planner_economy_filter_below_quota_peace_insufficient_regiments_routing_cases.dart';

void registerPhasePlannerEconomyFilterBelowQuotaPeaceInsufficientRegimentsCases() {
  registerPhasePlannerEconomyFilterBelowQuotaPeaceInsufficientRegimentsRoutingCases();
  registerPhasePlannerEconomyFilterBelowQuotaPeaceInsufficientRegimentsParityCases();
}
